# coding: utf-8

"""
    Interopdata API

    The Interopdata public API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.create_customer_dto import CreateCustomerDto
from openapi_client import configuration


class TestCreateCustomerDto(unittest.TestCase):
    """CreateCustomerDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
