# coding: utf-8

"""
    Interopdata API

    The Interopdata public API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class AccessToken(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "expiredAt",
            "customerId",
            "accessToken",
        }
        
        class properties:
            customerId = schemas.StrSchema
            accessToken = schemas.StrSchema
            expiredAt = schemas.StrSchema
            __annotations__ = {
                "customerId": customerId,
                "accessToken": accessToken,
                "expiredAt": expiredAt,
            }
    
    expiredAt: MetaOapg.properties.expiredAt
    customerId: MetaOapg.properties.customerId
    accessToken: MetaOapg.properties.accessToken
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["customerId"]) -> MetaOapg.properties.customerId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["accessToken"]) -> MetaOapg.properties.accessToken: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expiredAt"]) -> MetaOapg.properties.expiredAt: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["customerId", "accessToken", "expiredAt", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["customerId"]) -> MetaOapg.properties.customerId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["accessToken"]) -> MetaOapg.properties.accessToken: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expiredAt"]) -> MetaOapg.properties.expiredAt: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["customerId", "accessToken", "expiredAt", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        expiredAt: typing.Union[MetaOapg.properties.expiredAt, str, ],
        customerId: typing.Union[MetaOapg.properties.customerId, str, ],
        accessToken: typing.Union[MetaOapg.properties.accessToken, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AccessToken':
        return super().__new__(
            cls,
            *_args,
            expiredAt=expiredAt,
            customerId=customerId,
            accessToken=accessToken,
            _configuration=_configuration,
            **kwargs,
        )
