# coding: utf-8

"""
    Interopdata API

    The Interopdata public API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.customers.post import CreateCustomer
from openapi_client.paths.data_exports.post import CreateDataExport
from openapi_client.paths.data_export_datasets_id_download.post import CreateDataExportDatasetDownload
from openapi_client.paths.data_export_links.post import CreateDataExportLink
from openapi_client.paths.oauth_token.post import CreateOAuthToken
from openapi_client.paths.customers.get import CustomersList
from openapi_client.paths.data_export_datasets_id.get import DataExportDatasetRetrieve
from openapi_client.paths.data_exports_id.get import DataExportRetrieve
from openapi_client.paths.data_exports.get import DataExportsList
from openapi_client.paths.datasets.get import DatasetsList


class DefaultApi(
    CreateCustomer,
    CreateDataExport,
    CreateDataExportDatasetDownload,
    CreateDataExportLink,
    CreateOAuthToken,
    CustomersList,
    DataExportDatasetRetrieve,
    DataExportRetrieve,
    DataExportsList,
    DatasetsList,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
